version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: faz-pnb-container
    volumes:
      - .:/usr/src/app
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
    ports:
      - "5000:5000"
    command: ["python", "core/main.py"]
